services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: recrutamento_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Configurações base
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      # Ajuste de timezone
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      # O volume garante que não perdes os teus fluxos se o container for destruído
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: